use_frameworks!

platform :ios, '8.0'

target 'objective_c_core_helpers_Example' do
  pod 'objective_c_core_helpers', :path => '../'

  target 'objective_c_core_helpers_Tests' do
    inherit! :search_paths

    
  end
end
